/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_StringBuffer
#define HEADER_StringBuffer



#define STRINGBUFFER_BLOCK 256


typedef struct StringBuffer_ {
   char* buffer;
   int bufferSize;
   int usedSize;
} StringBuffer;


StringBuffer* StringBuffer_new(char* data);

void StringBuffer_delete(StringBuffer* this);

void StringBuffer_makeRoom(StringBuffer* this, int neededSize);

void StringBuffer_addChar(StringBuffer* this, char ch);

void StringBuffer_add(StringBuffer* this, char* str);

void StringBuffer_prepend(StringBuffer* this, char* str);

void StringBuffer_set(StringBuffer* this, const char* str);

void StringBuffer_addAll(StringBuffer* this, int n, ...);

void StringBuffer_printf(StringBuffer* this, char* format, ...);

void StringBuffer_addPrintf(StringBuffer* this, char* format, ...);

char* StringBuffer_getCopy(StringBuffer* this);

char* StringBuffer_getBuffer(StringBuffer* this);

char* StringBuffer_getRef(StringBuffer* this);

void StringBuffer_prune(StringBuffer* this);

#endif
